language: node_js
cache: npm
notifications:
  email: false
node_js:
  - "10"
script:
  - npm run test && npm run build
after_success:
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
